### ISSUE TITLE
Cannot import template in zabbix 4.2

### ISSUE THREAD

**Issue by Jensilein** [v-zhuravlev/zbx-smartctl#103]
Hello,

I tried to import the 3.4 template in zabbix 4.2 but I get the failure message

> Cannot read XML: (41) Specification mandates value for attribute data-pjax-transient [Line: 44 | Column: 92].

How can I make it work with zabbix 4.2? Would be great to find a solution.

Best regards

**Comment by v-zhuravlev** [comment]
This template works in 4.2 without any issues. Please make sure you are using the latest template from this repo.
![image](https://user-images.githubusercontent.com/14870891/59592015-db2d1f00-90f7-11e9-9d8d-dd65f71d71d8.png)


Please reopen if still having problems.

**Comment by Jensilein** [comment]
Hi Vitaly,

Thanks for your swift reply. Unfortunately it doesn‘t work for me. I always get the above mentioned error message. Maybe it is because I have zabbix running in a docker on ky Synology NAS? Or that doesn‘t matter at all? But how can I solve the problem?

Thanks and best regards.
