### ISSUE TITLE
Cannot import template in zabbix 4.2

### ISSUE THREAD

**Issue by Jensilein** [v-zhuravlev/zbx-smartctl#104]
This template works in 4.2 without any issues. Please make sure you are using the latest template from this repo.
![image](https://user-images.githubusercontent.com/14870891/59592015-db2d1f00-90f7-11e9-9d8d-dd65f71d71d8.png)

Please reopen if still having problems.

_Originally posted by @v-zhuravlev in https://github.com/v-zhuravlev/zbx-smartctl/issues/103#issuecomment-502598408_

**Comment by Jensilein** [comment]
Hi Vitaly,

Thanks for your swift reply. Unfortunately it doesn‘t work for me. I always get the above mentioned error message. Maybe it is because I have zabbix running in a docker on my Synology NAS or doesn’t that matter at all? But how can I solve the problem, do you have any idea?

Thanks and best regards.

**Comment by Jensilein** [comment]
Hello Vitaly, problem solved. Have downloaded the files again and now the import worked.

**Comment by v-zhuravlev** [comment]
Glad to hear that:)

Отправлено с телефона
