### ISSUE TITLE
Unsupported item key.

### ISSUE THREAD

**Issue by art-zhitnik** [v-zhuravlev/zbx-smartctl#11]
Template import goes well, no errors. But it brakes on discovery. Zabbix server (3.0) logs shows: 
`item "MYHOST:uHDD.discovery" became not supported: Unsupported item key.`
Smartmontools are installed as well as extra lines on zabbix agent (on windows machine)...

**Comment by v-zhuravlev** [comment]
Hi, please check that userparameter is added to zabbix_agentd.conf properly.
If it is fine, try to to use `zabbix_get -s *agentIP* -p 10050 -k uHDD.discovery` to see what output it gets

**Comment by art-zhitnik** [comment]
One thing I forgot to do is to restart zabbix agent))) Issue closed.
