### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by natict** [v-zhuravlev/zbx-smartctl#16]
Hi,

I'd love to use the discovery script at my current workplace, but need a proper license to be associated with it.
Adding a licence to your github repo should be fairly easy: https://help.github.com/articles/open-source-licensing/

Thanks!

**Comment by v-zhuravlev** [comment]
which one would you suggest?

**Comment by natict** [comment]
Personally I really like MIT's one, since it's simple and permissive.

**Comment by vazhnov** [comment]
+1, license information is very important for Open Source Zabbix.

**Comment by v-zhuravlev** [comment]
sorry guys, If you want to speed it up a bit, then you could make a merge request with licensing info and  I'll merge it.

**Comment by v-zhuravlev** [comment]
Thanks @vazhnov
