### ISSUE TITLE
Remove "sas" tag

### ISSUE THREAD

**Issue by allanbowe** [v-zhuravlev/zbx-smartctl#169]
Would you consider removing or re-naming the SAS tag in this repo? 

The vast majority of repositories under the "SAS" tag are in relation to **SAS Software**, not **Serial Attached SCSI**.  See:  https://github.com/topics/sas

Wouldn't be worth mentioning, except that this repo is in the top 10 repositories for "sas" !

**Comment by v-zhuravlev** [comment]
Sure, will do. :)

**Comment by allanbowe** [comment]
Thanks!
