### ISSUE TITLE
debhelper install file is incorrect

### ISSUE THREAD

**Issue by alllel** [v-zhuravlev/zbx-smartctl#21]
1. Syntax of _install_ file is: source_file destination_DIR, not dest_FILE
2. On Ubuntu, default directory for zabbix_agent configs is /etc/zabbix/zabbix_agentd.conf.d not just /etc/zabbix/zabbix_agentd.d

Proposed file zabbix-agent-extra-smartctl.install :
>  sudoers_zabbix_smartctl etc/sudoers.d
>  discovery-scripts/nix/smartctl-disks-discovery.pl usr/lib/zabbix/scripts
>  zabbix_smartctl.conf etc/zabbix/zabbix_agentd.conf.d

**Comment by v-zhuravlev** [comment]
@vazhnov , could you please comment on this? Thank you

**Comment by alllel** [comment]
One more thing: script should be done executable somehow.
Now it is packaged into deb as non-executable, so discovery does not work.

**Comment by alllel** [comment]
And one more thing: package should have postinst/postrm files to reload zabbix-agent on installation/deinstallation.
Something like that: debian/zabbix-agent-extra-smartctl.postinst
>#!/bin/sh
>
>set -e
>
>case $1 in 
>    configure)
>	invoke-rc.d zabbix-agent restart
>esac
>
>#DEBHELPER#
>
