### ISSUE TITLE
Ошибка импорта шаблона в Zabbix 3.2.3

### ISSUE THREAD

**Issue by mocart2** [v-zhuravlev/zbx-smartctl#26]
Не удалось прочитать XML: (41) Specification mandate value for attribute data-pjax-transient [Строка: 33 | Колонка: 90].

**Comment by mocart2** [comment]
решено: скопировал текст в буфер, создал xml руками, вставил, шаблон импортировался

**Comment by nezhivyi** [comment]
Скачивал из браузера и wget, только после клонирования или загрузки ZIP с GitHub XML не битый.
