### ISSUE TITLE
Discovery script does not have "execute" permissions in Debian package

### ISSUE THREAD

**Issue by kyllingstad** [v-zhuravlev/zbx-smartctl#27]
When I build and install the Debian package, `/etc/zabbix/scripts/smartctl-disks-discovery.pl` gets permissions 0644, and is therefore not runnable by zabbix-agent.

**Comment by kosfango** [comment]
Seem, you need to do:
chown -R zabbix:zabbix /etc/zabbix/scripts
and 
chmod 750 (or 700) -R /etc/zabbix/scripts
