### ISSUE TITLE
win smartctl-disks-discovery.ps1  based on loop index

### ISSUE THREAD

**Issue by eugpod** [v-zhuravlev/zbx-smartctl#47]
Hello
Thanks alot for templates. I myself is new to zabbix so my assumption might be wrong or irreleveant.
Disk numbering in windows/smartctl-disks-discovery.ps1 relies upon loop index
```
$idx = 0
...
foreach ($disk in $disks) {
.....
    $idx++;
}
```
and with multiple disks (in my case 4 hdd )
```WMIC diskdrive get  name```
\\.\PHYSICALDRIVE2
\\.\PHYSICALDRIVE3
\\.\PHYSICALDRIVE1
\\.\PHYSICALDRIVE0
they will be mapped incorrectly.
May I suggest slightly different approach in getting drive letter by disk index
```
$smartctl = "C:\Program Files\smartmontools\bin\smartctl.exe"

if ((Get-Command $smartctl -ErrorAction SilentlyContinue) -eq $null) 
{ 
   write-host "Unable to find smartctl"
   exit
}

$disks = GET-WMIOBJECT -query "SELECT * from win32_diskdrive"

[char[]] $abc_array = ([char]'a'..[char]'z')
$lines = @()
foreach ($disk in $disks)
{
 
    $dev_id = $disk|Out-String -stream | Select-String "DeviceID"
    $m = (([regex]'\d+').Match($dev_id))
    
    $smartctl_disk_name = "/dev/hd" + $abc_array[$m.Value]
    $smart_enabled = & $smartctl "-i" $smartctl_disk_name | select-string "SMART.+Enabled$"
 
    if($smart_enabled) {            
        $smart_enabled = 1
    } else {            
        $smart_enabled = 0
    }

    $line= "`t`t{`n " + "`t`t`t`"{#DISKNAME}`":`""+$smartctl_disk_name+"`""+ ",`n" + "`t`t`t`"{#SMART_ENABLED}`":`""+$smart_enabled+"`"" +"`n`t`t}"
    $lines += $line;
    
}
$data = $lines -join ",`n"
write-host "{`n`t`"data`": [`n" $data "`n`t]`n}"
```
Thanks again for your work

PS what if disk count in the system goes above English abc in 
```[char[]] $abc_array = ([char]'a'..[char]'z')```

**Comment by v-zhuravlev** [comment]
Hi, thank you.
WMI is no longer used for finding disks. smartctl is used instead. See #56.
