### ISSUE TITLE
Error : Can't use string ("disk0") as a HASH ref while "strict refs"

### ISSUE THREAD

**Issue by tifredfr** [v-zhuravlev/zbx-smartctl#53]
Hi,

I get the following error when I test the command under macOS 10.12.6 : 
`sudo -u zabbix ./smartctl-disks-discovery.pl`
`Can't use string ("disk0") as a HASH ref while "strict refs" in use at ./smartctl-disks-discovery.pl line 61.`

Thx ;)

**Comment by v-zhuravlev** [comment]
how your disks are called?
`ls -lah /dev/disk*`

**Comment by tifredfr** [comment]
The fix works for me :)

A big thank-you ;)
