### ISSUE TITLE
Discovery rules Value should be a JSON object

### ISSUE THREAD

**Issue by roderik-k** [v-zhuravlev/zbx-smartctl#61]
The discovery script ps1 for Win has a small mistake, its "comma" on line 20
in this case is not valid Json format, I dont know to correct the ps1 script to reduce  ","
![json](https://user-images.githubusercontent.com/40571968/41857929-e427670a-7898-11e8-892d-2e106f05e2aa.png)

thanks

zabbix_get:
--------------
{
 "data":[

	{
 		"{#DISKSN}":"xxxxxxxxxx",
		"{#DISKMODEL}":"SanDisk SD8SBAT-256G-1006",
		"{#DISKNAME}":"/dev/sda",
		"{#DISKCMD}":"/dev/sda -data",
		"{#SMART_ENABLED}":"1",
		"{#DISKTYPE}":"1"
	},

	{
 		"{#DISKSN}":"yyyyyyyyyyy",
		"{#DISKMODEL}":"hp PLDS DVDRW  DU8AESH",
		"{#DISKNAME}":"/dev/csmi0,1",
		"{#DISKCMD}":"/dev/csmi0,1 -data",
		"{#SMART_ENABLED}":"0",
		"{#DISKTYPE}":"2"
	},

 ]

**Comment by v-zhuravlev** [comment]
thanks, will try to fix it ASAP

**Comment by roderik-k** [comment]
thx for your support, 👍

**Comment by SimplyKot** [comment]
The same error:
`{
 "data":[

        {
                "{#DISKSN}":"Y21WK8JC",
                "{#DISKMODEL}":"Maxtor 6Y080M0",
                "{#DISKNAME}":"/dev/sda",
                "{#DISKCMD}":"/dev/sda -data",
                "{#SMART_ENABLED}":"1",
                "{#DISKTYPE}":"0"
        },

        {
                "{#DISKSN}":"",
                "{#DISKMODEL}":"",
                "{#DISKNAME}":"/dev/sdb",
                "{#DISKCMD}":"/dev/sdb -dscsi",
                "{#SMART_ENABLED}":"0",
                "{#DISKTYPE}":"2"
        },

        {
                "{#DISKSN}":"9QM7W1LD",
                "{#DISKMODEL}":"ST3500320AS",
                "{#DISKNAME}":"/dev/csmi0,1",
                "{#DISKCMD}":"/dev/csmi0,1 -data",
                "{#SMART_ENABLED}":"1",
                "{#DISKTYPE}":"0"
        },

        {
                "{#DISKSN}":"Z2AMFRRB",
                "{#DISKMODEL}":"ST500DM002-1BD142",
                "{#DISKNAME}":"/dev/csmi0,2",
                "{#DISKCMD}":"/dev/csmi0,2 -data",
                "{#SMART_ENABLED}":"1",
                "{#DISKTYPE}":"0"
        },

        {
                "{#DISKSN}":"Z3T83S3M",
                "{#DISKMODEL}":"ST500DM002-1BD142",
                "{#DISKNAME}":"/dev/csmi0,3",
                "{#DISKCMD}":"/dev/csmi0,3 -data",
                "{#SMART_ENABLED}":"1",
                "{#DISKTYPE}":"0"
        },


 ]
}
`

**Comment by v-zhuravlev** [comment]
mykolq  what powershell and Windowns versions do you have?

**Comment by mykolq** [comment]
5.1.14393.2248

**Comment by mykolq** [comment]
sure. ```
C:\zabbix_agent\smartmontools\bin>smartctl --scan-open
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/csmi2,0 -d ata # /dev/csmi2,0, ATA device
/dev/csmi2,1 -d ata # /dev/csmi2,1, ATA device
```

**Comment by v-zhuravlev** [comment]
Strange, can't find the reason of this extra comma.  Fixed problem with trim() function though(I hope): https://github.com/v-zhuravlev/zbx-smartctl/commit/9177c28b3dc26c793bb6283b1213eb5fffa5b076

**Comment by v-zhuravlev** [comment]
Ok, found the problem please try the latest commit

**Comment by mykolq** [comment]
thanks a lot =)  it works fine

**Comment by roderik-k** [comment]
thanks it works very nice, valid json format

**Comment by roderik-k** [comment]
I have this one host (dell) where something not working correctly: 
C:\Program Files\smartmontools\bin>smartctl.exe --scan-open
/dev/sda -d ata # /dev/sda, ATA device
/dev/csmi0,0 -d ata # /dev/csmi0,0, ATA device

valid json - powershell cmd on dell host local:
PS C:\zabbix_agent> .\smartctl-disks-discovery.ps1
{
 "data":[

        {
                "{#DISKSN}":"171616DFD067",
                "{#DISKMODEL}":"Micron 1100 SATA 256GB",
                "{#DISKNAME}":"/dev/sda",
                "{#DISKCMD}":"/dev/sda -data",
                "{#SMART_ENABLED}":"1",
                "{#DISKTYPE}":"2"
        }

 ]
}
=======================================
but in zabbix system is not valid json ("comma" error):
[root@monitoring ~]# zabbix_get -s 192.168.1.221 -p 10050 -k uHDD.discovery
{
 "data":[

	{
 		"{#DISKSN}":"171616DFD067",
		"{#DISKMODEL}":"Micron 1100 SATA 256GB",
		"{#DISKNAME}":"/dev/sda",
		"{#DISKCMD}":"/dev/sda -data",
		"{#SMART_ENABLED}":"1",
		"{#DISKTYPE}":"1"
	},


 ]
}

**Comment by v-zhuravlev** [comment]
Sorry! Was trying to fix that in a rush. Now it should work in your case as well.

**Comment by SimplyKot** [comment]
Still not working...
`Невозможно найти тип [ordered]: убедитесь в том, что сборка, содержащая этот тип, загружена.
C:\zabbix\conf\scripts\smartctl-disks-discovery.ps1:93 знак:24
+     $disks += [ordered] <<<< @{
    + CategoryInfo          : InvalidOperation: (ordered:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Невозможно найти тип [ordered]: убедитесь в том, что сборка, содержащая этот тип, загружена.
C:\zabbix\conf\scripts\smartctl-disks-discovery.ps1:93 знак:24
+     $disks += [ordered] <<<< @{
    + CategoryInfo          : InvalidOperation: (ordered:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Невозможно найти тип [ordered]: убедитесь в том, что сборка, содержащая этот тип, загружена.
C:\zabbix\conf\scripts\smartctl-disks-discovery.ps1:93 знак:24
+     $disks += [ordered] <<<< @{
    + CategoryInfo          : InvalidOperation: (ordered:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Невозможно найти тип [ordered]: убедитесь в том, что сборка, содержащая этот тип, загружена.
C:\zabbix\conf\scripts\smartctl-disks-discovery.ps1:93 знак:24
+     $disks += [ordered] <<<< @{
    + CategoryInfo          : InvalidOperation: (ordered:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Невозможно найти тип [ordered]: убедитесь в том, что сборка, содержащая этот тип, загружена.
C:\zabbix\conf\scripts\smartctl-disks-discovery.ps1:93 знак:24
+     $disks += [ordered] <<<< @{
    + CategoryInfo          : InvalidOperation: (ordered:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Невозможно найти тип [ordered]: убедитесь в том, что сборка, содержащая этот тип, загружена.
C:\zabbix\conf\scripts\smartctl-disks-discovery.ps1:93 знак:24
+     $disks += [ordered] <<<< @{
    + CategoryInfo          : InvalidOperation: (ordered:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Имя "ConvertTo-Json" не распознано как имя командлета, функции, файла скрипта или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите попытку.
C:\zabbix\conf\scripts\smartctl-disks-discovery.ps1:104 знак:46
+ $json_disks = @{data= $disks}| ConvertTo-Json <<<<  -Depth 2
    + CategoryInfo          : ObjectNotFound: (ConvertTo-Json:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by v-zhuravlev** [comment]
What windows and powershell version do you have?

**Comment by v-zhuravlev** [comment]
Ok, no fancy PS modules dependencies now, just fixed comma thing :)

**Comment by SimplyKot** [comment]
Now working great! Thank you!

**Comment by v-zhuravlev** [comment]
Finally ! 😆

**Comment by zetheroo** [comment]
I am experiencing this issue on a Debian Stretch (PVE) system running zabbix_agent 4.0.7

```
root@proxsat:/etc/zabbix/scripts# ./smartctl-disks-discovery.pl 
{
	"data":[

		{
			"{#DISKMODEL}":"WDC WD1003FZEX-00K3CA0",
			"{#DISKSN}":"WD-WCC6Y0NYF3E7",
			"{#DISKNAME}":"/dev/sda",
			"{#DISKCMD}":"/dev/sda -d sat",
			"{#SMART_ENABLED}":"1",
			"{#DISKTYPE}":"0"
		},
		{
			"{#DISKMODEL}":"WDC WD1003FZEX-00K3CA0",
			"{#DISKSN}":"WD-WCC6Y4KD46L2",
			"{#DISKNAME}":"/dev/sdb",
			"{#DISKCMD}":"/dev/sdb -d sat",
			"{#SMART_ENABLED}":"1",
			"{#DISKTYPE}":"0"
		},
		{
			"{#DISKMODEL}":"Samsung SSD 860 PRO 1TB",
			"{#DISKSN}":"S42NNF0K501976K",
			"{#DISKNAME}":"/dev/sdc",
			"{#DISKCMD}":"/dev/sdc -d sat",
			"{#SMART_ENABLED}":"1",
			"{#DISKTYPE}":"1"
		},
		{
			"{#DISKMODEL}":"Samsung SSD 860 PRO 1TB",
			"{#DISKSN}":"S42NNF0K501910F",
			"{#DISKNAME}":"/dev/sdd",
			"{#DISKCMD}":"/dev/sdd -d sat",
			"{#SMART_ENABLED}":"1",
			"{#DISKTYPE}":"1"
		}
	]
}

```

**Comment by TiratoreA** [comment]
![image](https://user-images.githubusercontent.com/17968479/60605091-8eb53500-9dc1-11e9-9076-b56c3a3fcbc2.png)

I have the same error in Linux

**Comment by TiratoreA** [comment]
# smartctl --scan-open
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/sdb -d sat # /dev/sdb [SAT], ATA device
/dev/bus/0 -d megaraid,0 # /dev/bus/0 [megaraid_disk_00], SCSI device
/dev/bus/0 -d megaraid,1 # /dev/bus/0 [megaraid_disk_01], SCSI device
/dev/bus/0 -d megaraid,2 # /dev/bus/0 [megaraid_disk_02], SCSI device
/dev/bus/0 -d megaraid,3 # /dev/bus/0 [megaraid_disk_03], SCSI device
/dev/bus/0 -d megaraid,4 # /dev/bus/0 [megaraid_disk_04], SCSI device
/dev/bus/0 -d megaraid,5 # /dev/bus/0 [megaraid_disk_05], SCSI device
/dev/bus/0 -d megaraid,6 # /dev/bus/0 [megaraid_disk_06], SCSI device
/dev/bus/0 -d megaraid,7 # /dev/bus/0 [megaraid_disk_07], SCSI device
