### ISSUE TITLE
Braking uHDD parameter if using comma in #DISKNAME or #DISKCMD

### ISSUE THREAD

**Issue by SimplyKot** [v-zhuravlev/zbx-smartctl#62]
Don't working with this configuration:

> {
>  "data":[
>          {
>                 "{#DISKSN}":"9QM7W1LD",
>                 "{#DISKMODEL}":"ST3500320AS",
>                 "{#DISKNAME}":"/dev/csmi0,1",
>                 "{#DISKCMD}":"/dev/csmi0,1 -data",
>                 "{#SMART_ENABLED}":"1",
>                 "{#DISKTYPE}":"0"
>          }
>  ]
> }

Example:

> uHDD["/dev/csmi0,1 -data",Temperature_Celsius]

executes following command on host:

> for /F "tokens=10 usebackq" %a in ('""C:\Program Files\smartmontools\bin\smartctl.exe" -A /dev/csmi0 | find "1""') do @echo %a

**Comment by v-zhuravlev** [comment]
No idea how to fix it now... how about  `uHDD.A[*]` ?

**Comment by SimplyKot** [comment]
> how about uHDD.A[*] ?

 It's working. Thank you.
