### ISSUE TITLE
Error in "Power On Hours"  on Maxtor 6Y080M0

### ISSUE THREAD

**Issue by SimplyKot** [v-zhuravlev/zbx-smartctl#63]
`zabadmin@zabbix-server:~$ zabbix_get -s 192.168.100.4 -k 'uHDD.model.["/dev/sda -data"]'
 Maxtor 6Y080M0`
 `zabadmin@zabbix-server:~$ zabbix_get -s 192.168.100.4 -k 'uHDD["/dev/sda -data",Power_On]'
 895h+03m`

/dev/sda: ID 9 Power On Hours
Received value [895h+01m] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

**Comment by v-zhuravlev** [comment]
Please use template for Zabbix 3.4 if you can. 895h+03m can be parsed there properly with preprocessing

**Comment by v-zhuravlev** [comment]
Can you use 3.4?

**Comment by SimplyKot** [comment]
No, i can't.
Now i just disable this parameter
