### ISSUE TITLE
Обрабатывать результаты теста

### ISSUE THREAD

**Issue by Makishima** [v-zhuravlev/zbx-smartctl#64]
Привет.
Может стоит для агента 3.4 для параметра состояния добавить обработку `| grep "test"| cut -f2 -d: | tr -d " "`, чтобы получать или `PASSED`, или `FAILED` без не нужного текста?

**Comment by v-zhuravlev** [comment]
там бывают и другие варианты...  и весь парсинг начиная с 3.4 буду по возможности делать на стороне заббикс сервера, чтобы работало для инфы полученной с Windows так и для Linux

**Comment by Makishima** [comment]
А разве начальная часть _... SMART overall-health self-assessment test result:_ не одинакова для всех вариантов?
А на стороне заббикса оно удобнее будет, да.

**Comment by v-zhuravlev** [comment]
fixed in e727d1a13913a20f56ad4ce1e37f1c64c6638a0b
