### ISSUE TITLE
Некорректные данные с Windows агента

### ISSUE THREAD

**Issue by iverlord** [v-zhuravlev/zbx-smartctl#65]
Ставил всё по инструкции, однако данные на сервере не видны. Единственное, что есть - в элементе TestResult непонятная строка  ???।???????? ??????: ProgramFilesa.  Windows 7, Server 2003, PowerShell 1.0

**Comment by v-zhuravlev** [comment]
попробуйте проверить через zabbix_get
Скорей всего неверный путь в UserParameterрах

**Comment by iverlord** [comment]
Проблемы действительно была в путях, видимо криво скопировалось
