### ISSUE TITLE
Zabbix 4.0 Template Import

### ISSUE THREAD

**Issue by XplizitBe** [v-zhuravlev/zbx-smartctl#70]
I have a problem with importing the template into Zabbix 4.0. It imports without errors but only application, and discovery script get import. No items no triggers?

Querying by hand through zabbix_get works fine.

**Comment by mykolq** [comment]
it seems there is a problem with regexp in preprocessing. you can fix it by yourself by 
taking the expression in parentheses and getting non first matching. example:
![2018-10-25_16-48-23](https://user-images.githubusercontent.com/935567/47504905-cef90680-d875-11e8-8853-e8a2fb7d5009.png)

**Comment by v-zhuravlev** [comment]
@XplizitBe  which template? Template for 3.4, for example, doesn't have any items or triggers - everything is discovered by LLD, so see the discovery section inside the template - where you would find items and trigger prototypes.

**Comment by mykolq** [comment]
![2018-12-10_11-39-35](https://user-images.githubusercontent.com/935567/49720242-58229c00-fc70-11e8-851d-0d56b4798019.png)
something like that.  You can check expressions here [https://regex101.com/](url).

**Comment by v-zhuravlev** [comment]
@jpaulickcz , can you please attach `smartctl -A` output?

**Comment by v-zhuravlev** [comment]
closing this now, please reopen if still having issues.
