### ISSUE TITLE
Cannot create item: item with the same key 

### ISSUE THREAD

**Issue by Kleusov** [v-zhuravlev/zbx-smartctl#72]
Привет. Спасибо за проделанную работу.

На одном хосте всё прекрасно работает.

Когда хочу подключить к другому возникает ошибка: "Cannot create item: item with the same key" у каждого item.

Что это может быть ?

**Comment by Kleusov** [comment]
Zabbix 4.0

**Comment by v-zhuravlev** [comment]
Привет, какой шаблон, для 3.4?

**Comment by v-zhuravlev** [comment]
Закрываю, откройте снова, если еще актуално.
