### ISSUE TITLE
Не корректные данные параметров для Smartctl

### ISSUE THREAD

**Issue by raegent** [v-zhuravlev/zbx-smartctl#81]
Добрый день, спасибо за вашу работу. 
Имею Zabbix 4.2, Ubuntu 16.04.6, smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.15.0-47-generic]

Вывод - все отлично: /etc/zabbix/scripts/smartctl-disks-discovery.pl
{
        "data":[

                {
                        "{#DISKMODEL}":"64GB SSD",
                        "{#DISKSN}":"H42795J001891",
                        "{#DISKNAME}":"/dev/sda",
                        "{#DISKCMD}":"/dev/sda -d sat",
                        "{#SMART_ENABLED}":"1",
                        "{#DISKTYPE}":"1"
                },
                {
                        "{#DISKMODEL}":"WDC WD40PURZ-85TTDY0",
                        "{#DISKSN}":"WD-WCC7K0TRFN79",
                        "{#DISKNAME}":"/dev/sdb",
                        "{#DISKCMD}":"/dev/sdb -d sat",
                        "{#SMART_ENABLED}":"1",
                        "{#DISKTYPE}":"0"
                },

Но в самом мониторинге имею текст ошибки: 
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.15.0-47-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

Smartctl open device: /dev//dev/sda [SAT] failed: No such device

Лишний /dev/ как я полагаю. Где это я смогу поправить?

**Comment by v-zhuravlev** [comment]
а какой шаблон используете?

**Comment by raegent** [comment]
> 
> 
> а какой шаблон используете?

Template_3.4_HDD_SMARTMONTOOLS_2_WITH_LLD.xml

**Comment by v-zhuravlev** [comment]
Возможно кто-то в шаблон вносил изменения? Если посмотреть файл https://github.com/v-zhuravlev/zbx-smartctl/blob/master/Template_3.4_HDD_SMARTMONTOOLS_2_WITH_LLD.xml то тут нигде dev не упоминается, поэтому задвоения быть не должно.

**Comment by v-zhuravlev** [comment]
Проблема все еще актуальна?

**Comment by v-zhuravlev** [comment]
Откройте заново, еесли еще актуально. Рекомендую также обновить шаблон, userparameters, скрипт, сегодня внес большие обновления.
