### ISSUE TITLE
Zabbix 4.0 uHDD.discovery not Supported on Windows

### ISSUE THREAD

**Issue by DerP9** [v-zhuravlev/zbx-smartctl#82]
Hello,

i have imported the Template_HDD_SMARTMONTOOLS_2_WITH_LDD.
But in the Discovery rules the status is: Not Supported. 

![Unbenannt](https://user-images.githubusercontent.com/12477142/56139462-38421280-5f99-11e9-8be0-8c5fd42a8a41.JPG)

How Can i find out what is going wrong?

Kind regards

**Comment by v-zhuravlev** [comment]
Have you installed the powershell script properly? 
As well as installing useraparameter in the Zabbix agent config. 
Please double check how to set this up properly in README again.

**Comment by v-zhuravlev** [comment]
please reopen if still having a problem.
