### ISSUE TITLE
tested 3.0.1 centos7

### ISSUE THREAD

**Issue by agrisvv** [v-zhuravlev/zbx-smartctl#9]
in
` /etc/sudoers.d`
add
`Defaults:zabbix    !requiretty`
`zabbix ALL= (ALL) NOPASSWD: /usr/sbin/smartctl,/usr/local/bin/smartctl-disks-discovery.pl`

from author template I just delete some not configured tags. With them can't import.
Rename txt to xml and import.
[Template_HDD_SMARTMONTOOLS_3_WITH_LLD.txt](https://github.com/v-zhuravlev/zbx-smartctl/files/186246/Template_HDD_SMARTMONTOOLS_3_WITH_LLD.txt)

**Comment by v-zhuravlev** [comment]
Thanks for pointing this out. It seems that if change    version tag to  <version>3.0</version> template can be successfully imported as well.
