### ISSUE TITLE
Permanently lit SMART trigger status is not OK

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [v-zhuravlev/zbx-smartctl#98]
Trigger SMART status is not OK constantly in the Problem state for all disks.

**Comment by AntonAndreevichMoroz** [comment]
But in fact, all results get PASSED. Why does the trigger fire?

**Comment by v-zhuravlev** [comment]
please show me trigger expression and what is the value that you have?

**Comment by v-zhuravlev** [comment]
Is client Windows or Linux?

**Comment by v-zhuravlev** [comment]
My guess is that there is a whitespace character in the output. 
Try changing regex in preprocessing step for something like this?
`(?:SMART overall-health self-assessment test result:|SMART Health Status:) +\b([\S ]+)`
or if this doesn't help. maybe even this:
`(?:SMART overall-health self-assessment test result:|SMART Health Status:) +\b([\w ]+)`

**Comment by AntonAndreevichMoroz** [comment]
Windows client.
I eventually made these conditions for the trigger. Unfortunately, I don’t know how to imitate 100% of a poor SMART state, but changing the text in a macro gives the correct triggering effect. Please give your expert opinion how much it is correct. Thank you in advance.
{Template_HDD_SMARTMONTOOLS_2_WITH_LLD:uSSD.health["{#DISKCMD}"].iregexp({$SMARTCTL_OK_STATUS:"SATA"},#1)}=0 and {Template_HDD_SMARTMONTOOLS_2_WITH_LLD:uSSD.health["{#DISKCMD}"].iregexp({$SMARTCTL_OK_STATUS:"SAS"},#1)}=0

**Comment by v-zhuravlev** [comment]
Can you try to revert trigger expression back and the line I suggested in this item preprocessing?
`(?:SMART overall-health self-assessment test result:|SMART Health Status:) +\b([\S ]+)`

**Comment by gijoe88** [comment]
The new regexp (with \S) solved the issue for me. I don't think it was linked to there being a space in the result, but to "line endings" of windows having "\r\n", the \r being caught by "." when on unix server.
